nbisL1-trna-1	nbisL1-trna-1	Gene	Expression
nbisL1-trna-2	nbisL1-trna-2	Gene	Expression
MT-ND2	MT-ND2	Gene	Expression
nbisL1-trna-4	nbisL1-trna-4	Gene	Expression
nbisL1-trna-5	nbisL1-trna-5	Gene	Expression
MT-COX1	MT-COX1	Gene	Expression
MT-COX2	MT-COX2	Gene	Expression
nbisL1-trna-8	nbisL1-trna-8	Gene	Expression
MT-ATP-8	MT-ATP-8	Gene	Expression
MT-ATP-6	MT-ATP-6	Gene	Expression
MT-COX3	MT-COX3	Gene	Expression
MT-ND3	MT-ND3	Gene	Expression
nbisL1-trna-11	nbisL1-trna-11	Gene	Expression
nbisL1-trna-12	nbisL1-trna-12	Gene	Expression
nbisL1-trna-13	nbisL1-trna-13	Gene	Expression
nbisL1-trna-14	nbisL1-trna-14	Gene	Expression
nbisL1-trna-15	nbisL1-trna-15	Gene	Expression
MT-ND5	MT-ND5	Gene	Expression
MT-ND4	MT-ND4	Gene	Expression
MT-ND4L	MT-ND4L	Gene	Expression
nbisL1-trna-18	nbisL1-trna-18	Gene	Expression
MT-ND6	MT-ND6	Gene	Expression
MT-CYTB	MT-CYTB	Gene	Expression
MT-ND1	MT-ND1	Gene	Expression
nbisL1-trna-21	nbisL1-trna-21	Gene	Expression
nbisL1-rrna-1	nbisL1-rrna-1	Gene	Expression
nbisL1-trna-22	nbisL1-trna-22	Gene	Expression
nbisL1-rrna-2	nbisL1-rrna-2	Gene	Expression
match1	match1	Gene	Expression
match2	match2	Gene	Expression
